### ISSUE TITLE
Error while eval_cityscapes

### ISSUE THREAD

**Issue by jhtao1860** [ZijunDeng/pytorch-semantic-segmentation#10]
I change some code in eval_cs to fit CityScapes,the error  happened as following

File "eval/eval_cs.py", line 58, in <module>
    main()
  File "eval/eval_cs.py", line 42, in main
    for vi, data in enumerate(test_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 112, in default_collate
    .format(type(batch[0]))))
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'PIL.Image.Image'>

**Comment by ZijunDeng** [comment]
*TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'PIL.Image.Image'>* This line tells that you should convert the PIL Image object to torch Tensor object (see the torchvision.ToTensor function)
