### ISSUE TITLE
TypeError: 'torch.FloatTensor' object does not support indexing

### ISSUE THREAD

**Issue by lxtGH** [ZijunDeng/pytorch-semantic-segmentation#23]
When I train the FCN8S model it shows error at the end of epoch 1
[epoch 1], [iter 8440 / 8498], [train loss 545605.78962]
[epoch 1], [iter 8460 / 8498], [train loss 545628.17753]
[epoch 1], [iter 8480 / 8498], [train loss 545635.63007]
Traceback (most recent call last):
  File "train.py", line 214, in <module>
    main(args)
  File "train.py", line 98, in main
    val_loss = validate(val_loader, net, criterion, optimizer, epoch, train_args, restore_transform, visualize)
  File "train.py", line 190, in validate
    writer.add_image(snapshot_name, val_visual)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/tensorboard/writer.py", line 221, in add_image
    self.file_writer.add_summary(image(tag, img_tensor))
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/tensorboard/summary.py", line 174, in image
    tensor = np.ndarray(tensor, dtype=np.float32)
TypeError: 'torch.FloatTensor' object does not support indexing

**Comment by lxtGH** [comment]
solved by import tensorboardX

**Comment by elcucho1** [comment]
hello
