### ISSUE TITLE
Crashing intermittently when training psp_net with VOC dataset.

### ISSUE THREAD

**Issue by andreasrobinson** [ZijunDeng/pytorch-semantic-segmentation#29]
I have been getting this error consistently before it manages complete a single epoch:

[epoch 1], [iter 630 / 8498], [train main loss 1.32866], [train aux loss 1.31173]. [lr 0.0049055503]
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    main()
  File "train.py", line 105, in main
    train(train_loader, net, criterion, optimizer, curr_epoch, args, val_loader, visualize)
  File "train.py", line 113, in train
    for i, data in enumerate(train_loader):
  File "/home/andreas/anaconda2/envs/env/lib/python2.7/site-packages/torch/utils/data/dataloader.py",
line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/andreas/anaconda2/envs/env/lib/python2.7/site-packages/torch/utils/data/dataloader.py",
line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/andreas/anaconda2/envs/env/lib/python2.7/site-packages/torch/utils/data/dataloader.py",
line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/andreas/Dropbox/src/pytorch-semantic-segmentation/datasets/voc.py", line 99, in __getite
m__
    img, mask = torch.stack(img_slices, 0), torch.stack(mask_slices, 0)
  File "/home/andreas/anaconda2/envs/env/lib/python2.7/site-packages/torch/functional.py", line 59, in
 stack
    raise ValueError("stack expects a non-empty sequence of tensors")
ValueError: stack expects a non-empty sequence of tensors

**Comment by lzj322** [comment]
I met the same problem. It seems that the data augmentation codes don't work well. Can you check it? @ZijunDeng

**Comment by zhijiew** [comment]
@andreasrobinson 
@lzj322 
Have you fix this problems? I also met the same problem

**Comment by zhijiew** [comment]
I find it!

This error is caused by some training data, maybe there are some error when preprocess data, so I just delete them and my training code can run.

just delete these lines in train.txt:
724,
1237,
3572,
3920,
4688,
7031,

**Comment by lzj322** [comment]
@littlebelly , can you get a successful training result? Do you change any of author's codes?

**Comment by zhijiew** [comment]
I can train the network after delete training data I mentioned above, but there are still some errors in validate process, so I just give it up and use caffe code provided by offical author.

I feel that these errors caused by image slice operation which is needed in cityscape dataset because of the large image size, but unnecessary in voc2012 dataset.

I hope @ZijunDeng can help to solve these errors~

**Comment by lzj322** [comment]
@littlebelly 
 thank you for your reply. I changed the codes and remove the slice operation. But I still meet a problem in the model.
![error](https://user-images.githubusercontent.com/570646/34934656-3ba5488c-fa16-11e7-924b-462d8dac3337.png)


Have you meet this error before?

**Comment by iliadsouti** [comment]
Maybe trying to revert to this [commit](https://github.com/ZijunDeng/pytorch-semantic-segmentation/commit/308aa09828352ec089a1a0c52880ba5023de8288#diff-5d1c3e8860939df5795d2daf452ab324) may help solve all the problems. After that try to make the code compatible with python3 version.

**Comment by zijundeng** [comment]
Hi everyone, it seems there are some problems with the VOC dataset loader. I will check the code and fix bugs later on (I am busy for other things currently :-( ).

**Comment by lzj322** [comment]
@iliadsouti  It really works, thank you very much.

**Comment by peteflorence** [comment]
+1 confirmed that @iliadsouti 's suggestion of reverting to that commit averts the issue with the input to batch norm for PSPNet.  If I have time I'll try to PR a fix to current master
