### ISSUE TITLE
Can't pickle local object 'main.<locals>.<lambda>'

### ISSUE THREAD

**Issue by CarryChouMST** [ZijunDeng/pytorch-semantic-segmentation#63]
When I try to run the train.py, it reports an error like this:

- Can't pickle local object 'main.<locals>.<lambda>'

is there anyone know why? And how can I reslove it?

**Comment by CarryChouMST** [comment]
This is the reports:
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'

**Comment by CarryChouMST** [comment]
```
Traceback (most recent call last):
  File "D:/deep_learning/pytorch_semantic_segmentation_master/train.py", line 220, in <module>
    main(args)
  File "D:/deep_learning/pytorch_semantic_segmentation_master/train.py", line 103, in main
    train(train_loader, net, criterion, optimizer, epoch, train_args)
  File "D:/deep_learning/pytorch_semantic_segmentation_master/train.py", line 111, in train
    for i, data in enumerate(train_loader):
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\carrychou\anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'
```
