### ISSUE TITLE
Error  while train

### ISSUE THREAD

**Issue by jhtao1860** [ZijunDeng/pytorch-semantic-segmentation#9]
error happened while training, hope you can help me
Traceback (most recent call last):
  File "train/cityscapes-psp_net/train2.py", line 252, in <module>
    main()
  File "train/cityscapes-psp_net/train2.py", line 110, in main
    train(train_loader, net, criterion, optimizer, curr_epoch, args, val_loader, restore_transform, visualize)
  File "train/cityscapes-psp_net/train2.py", line 159, in train
    validate(val_loader, net, criterion, optimizer, curr_epoch, train_args, restore, visualize)
  File "train/cityscapes-psp_net/train2.py", line 182, in validate
    outputs,aa = net(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/htjiang/Desktop/pytorch-semantic-segmentation/models/psp_net.py", line 79, in forward
    x = self.final(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

**Comment by ZijunDeng** [comment]
Try to comment the line “cudnn.benchmark=True” and run again.

**Comment by jhtao1860** [comment]
@ZijunDeng  “cudnn.benchmark=True” is already wrotten in the code,i will try false
